package com.bitpunchlab.android.shareroutes


enum class ShareRouteState {
    NORMAL,
    START,
    ADD_MARKER,
    ROUTE_TO_BE_CREATED,
    CREATING_ROUTE,
    ROUTE_CREATED,
    CLEAN_ROUTE,
    TO_BE_SHARED,
    SAVE_ROUTE,
    CANCEL_SHARING,
    SHARED,
    RESTART
}

enum class SuggestRoutesState {
    NORMAL,
    START,
    PICK_LOCATION,
    CLEAN_CLICK_LISTENER,
    CONFIRMED_LOCATION,
    SEARCHING,
    DISPLAY_ROUTES,
    DISPLAY_CHOSEN,
    CLEAR_ROUTE,
    END,
    RESTART
}

enum class UserAccountState {
    NORMAL,
    UPDATE_EMAIL_READY,
    UPDATE_EMAIL_DATA_ERROR,
    UPDATE_EMAIL_SERVER_ERROR,
    UPDATE_EMAIL_PASSWORD_ERROR,
    UPDATE_EMAIL_SUCCESS,
    UPDATE_PASSWORD_READY,
    UPDATE_PASSWORD_DATA_ERROR,
    UPDATE_PASSWORD_SERVER_ERROR,
    UPDATE_PASSWORD_LOGIN_ERROR,
    UPDATE_PASSWORD_SUCCESS,
    LOGGED_OUT_USER
}